# Generated by Django 5.0.6 on 2024-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Roll', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
